# Problem 1: Collaborative Filtering for Recommending Songs to Music Listeners

* Recommendation  engines  are  vital  to  many  of  today’s  most  successful  firms.   From  Amazon  to Netflix to Spotify, companies have realized the value of automatically showing customers products they are more interested in purchasing based on the collaborative evaluations of products by customers,  and  based  also  on  customer-specific  and  product-specific  data  as  well.   

* In  this  problem, we provide you with data consisting of derived user ratings of songs based on each user’s listening behavior, obtained from the Million Song Dataset Project.  (Note that users do not actually rate songs – rather the “rating” has been determined from their listening behaviors – but we will stil luse phrases like “user 'i' has rated song 'j' ”, etc.)  

* Each user only listens to a few songs, and therefore for each user we only have rating data concerning these few songs.  Nevertheless, we would like to infer each user’s ratings of all songs based on the entirety of the data.  

**The summary goal of this problem will be to recommend specific songs to specific users.**

* The  data  for  this  problem  has  already  been  split  into  training,  validation,  and  test  sets  and  is provided in four .csv files: **MusicRatingsTrain.csv(85%)**, **MusicRatingsValidationA.csv(5%)**, **MusicRatingsValidationB.csv(5%)**, and **MusicRatingsTest.csv(5%)**.  

**Validation set A will be used for  hyperparameter  tuning  of  individual  models,  and  validation  set  B  will  be  used  for  blending.**

* Each observation corresponds to a user who has rated a particular song.  Table 1 below describes the columns of this data.

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import statistics

### Importing the data

In [2]:
music_ratings_train = pd.read_csv('MusicRatingsTrain.csv')
music_ratings_test = pd.read_csv('MusicRatingsTest.csv')
music_ratings_ValA = pd.read_csv('MusicRatingsValidationA.csv')
music_ratings_ValB = pd.read_csv('MusicRatingsValidationB.csv')

In [3]:
music_ratings_train

,userID,songID,rating,songName,year,artist,genre
0,2071,581,2.484754,Show You How,2004,The Killers,Rock
1,1208,55,1.000000,Luvstruck,1999,Southside Spinners,Electronic
2,1484,510,1.000000,In One Ear,2008,Cage The Elephant,Rock
3,453,299,1.000000,Gardenhead / Leave Me Alone,1992,Neutral Milk Hotel,Rock
4,2238,113,1.000000,Hustler,2006,Simian Mobile Disco,Electronic
...,...,...,...,...,...,...,...
245992,1513,720,1.000000,Trani,2003,Kings Of Leon,Rock
245993,443,544,1.000000,A Rush Of Blood To The Head,2002,Coldplay,Rock
245994,2172,706,1.784426,Without Me,2002,Eminem,Rap
245995,1714,699,1.494918,Cherbourg,2007,Beirut,Folk
245996,2195,753,1.494918,Bitter Sweet Symphony,1997,The Verve,Pop

In [4]:
music_ratings_train.shape

(245997, 7)

In [5]:
music_ratings_test

,userID,songID,rating,songName,year,artist,genre
0,853,54,1.989836,You're The One,1990,Dwight Yoakam,Country
1,608,34,1.000000,Nah!,2002,Shania Twain,Country
2,9,54,3.969507,You're The One,1990,Dwight Yoakam,Country
3,1862,54,2.279344,You're The One,1990,Dwight Yoakam,Country
4,329,80,1.494918,Tim McGraw,2006,Taylor Swift,Country
...,...,...,...,...,...,...,...
14466,443,615,1.494918,Daylight,2002,Coldplay,Rock
14467,1061,657,1.000000,Kissy Kissy,2003,The Kills,Rock
14468,610,653,1.000000,The Laws Have Changed,2003,The New Pornographers,Rock
14469,690,657,1.000000,Kissy Kissy,2003,The Kills,Rock
14470,230,657,1.000000,Kissy Kissy,2003,The Kills,Rock

In [6]:
music_ratings_test.shape

(14471, 7)

In [7]:
music_ratings_ValA

,userID,songID,rating,songName,year,artist,genre
0,1420,787,1.000000,Ragoo,2007,Kings Of Leon,Rock
1,2110,503,1.494918,In The End (Album Version),2000,Linkin Park,Rock
2,513,190,1.989836,Not Fair (Clean Radio Edit),2009,Lily Allen,Pop
3,1323,688,1.494918,A Message,2005,Coldplay,Rock
4,431,467,1.000000,I Will Follow You into the Dark (Album Version),2005,Death Cab for Cutie,Rock
...,...,...,...,...,...,...,...
14465,1118,721,1.000000,Milk,2004,Kings Of Leon,Country
14466,442,59,1.000000,They Might Follow You,2007,Tiny Vipers,Pop
14467,1975,217,1.000000,One More Sad Song,2001,The All-American Rejects,Rock
14468,1712,472,1.494918,Anything New,2007,Digitalism,Electronic
14469,399,716,1.494918,Time To Pretend,2005,MGMT,Rock

In [8]:
music_ratings_ValA.shape

(14470, 7)

In [9]:
music_ratings_ValB

,userID,songID,rating,songName,year,artist,genre
0,2102,13,1.494918,Such Great Heights,2003,The Postal Service,Electronic
1,1350,320,1.000000,The Shrew,2009,Beirut,Folk
2,947,7,1.494918,Halo,2008,Beyonce,Pop
3,175,558,1.989836,The Middle,2001,Jimmy Eat World,Rock
4,1984,445,1.494918,Daddy,2003,Beyonce,RnB
...,...,...,...,...,...,...,...
14466,1268,712,1.494918,Street Justice,2006,MSTRKRFT,Rock
14467,1154,575,4.480967,Hide & Seek,2009,Imogen Heap,Pop
14468,1640,367,1.000000,Holy Roller Novocaine,2003,Kings Of Leon,Rock
14469,2358,721,1.000000,Milk,2004,Kings Of Leon,Country
14470,2074,33,1.000000,Rhineland (Heartland),2005,Beirut,Rock

In [10]:
music_ratings_ValB.shape

(14471, 7)

#### Sorting the datasets by userId and songID

In [11]:
music_ratings_train = music_ratings_train.sort_values(by=['userID', 'songID'])

In [12]:
music_ratings_train.head()

,userID,songID,rating,songName,year,artist,genre
116572,1,10,1.784426,Harder Better Faster Stronger,2007,Daft Punk,Electronic
63286,1,22,1.000000,Up Up & Away,2009,Kid Cudi,Rap
219232,1,26,3.451920,Undo,2001,Bjork,Rock
243057,1,34,1.000000,Nah!,2002,Shania Twain,Country
103269,1,35,1.784426,Imma Be,2009,Black Eyed Peas,Rap

In [13]:
music_ratings_test = music_ratings_test.sort_values(by=(['userID', 'songID']))
music_ratings_test.head()

       userID  songID    rating               songName  year      artist genre
3187        1       7  1.989836                   Halo  2008     Beyonce   Pop
2211        1     753  1.784426  Bitter Sweet Symphony  1997   The Verve   Pop
2837        2      72  1.784426                  Teeth  2009   Lady GaGa   Pop
11793       2     481  1.000000              Waterfall  1978  Triumvirat  Rock
12493       2     507  1.784426                 Yellow  2000    Coldplay  Rock

In [14]:
music_ratings_ValA = music_ratings_ValA.sort_values(by=['userID', 'songID'])
music_ratings_ValA.head()

,userID,songID,rating,songName,year,artist,genre
364,1,25,1.000000,Seven Nation Army,2003,The White Stripes,Rock
12933,1,77,1.000000,Enter Sandman,1991,Metallica,Rock
11337,1,600,3.404302,Revelry,2008,Kings Of Leon,Rock
3036,1,635,2.484754,Make Love To Your Mind,1975,Bill Withers,RnB
1311,2,22,2.831414,Up Up & Away,2009,Kid Cudi,Rap

In [15]:
music_ratings_ValB = music_ratings_ValB.sort_values(by=['userID', 'songID'])
music_ratings_ValB.head()

,userID,songID,rating,songName,year,artist,genre
2523,1,93,1.989836,Clocks,2002,Coldplay,Rock
3773,1,462,1.000000,Rabbit Heart (Raise It Up),2009,Florence + The Machine,Rock
1777,1,663,1.784426,Tighten Up,2010,The Black Keys,Electronic
7897,2,24,1.000000,Swallowed In The Sea,2005,Coldplay,Electronic
1956,2,47,1.000000,I Stand Corrected (Album),2007,Vampire Weekend,Rock

## 1a) 
**How  many  songs  are  in  the  training  dataset?   How  many  users?   Based  on  the training set, provide summary statistics (mean, median, standard deviation, min, and max) for the rating variable.**

In [17]:
songs_train_len = len(music_ratings_train['songID'].unique())
print(f'There are {songs_train_len} unique songs in the training dataset.')

There are 807 unique songs in the training dataset.

In [18]:
users_train_len = len(music_ratings_train['userID'].unique())
print(f'There are {users_train_len} unique users in the training dataset.')

There are 2421 unique users in the training dataset.

In [21]:
# Summary Statistics Table for Rating Variable
music_ratings_train.describe()[['rating']]

              rating
count  245997.000000
mean        1.321962
std         0.459894
min         1.000000
25%         1.000000
50%         1.000000
75%         1.494918
max         4.768656

In [23]:
print(f'Mean of the rating variable is {music_ratings_train.describe()['rating']['mean']}')

Mean of the rating variable is 1.3219620891310984

In [26]:
print(f'Median of the rating variable is {music_ratings_train.describe()['rating']['50%']}')

Median of the rating variable is 1.0

In [27]:
print(f'Standard Devation of the rating variable is {music_ratings_train.describe()['rating']['std']}')

Standard Devation of the rating variable is 0.45989367021737887

In [28]:
print(f'Min of the rating variable is {music_ratings_train.describe()['rating']['min']}')

Min of the rating variable is 1.0

In [29]:
print(f'Max of the rating variable is {music_ratings_train.describe()['rating']['max']}')

Max of the rating variable is 4.768655987487031

## 1b)
Let **X** denote the “complete” ratings matrix, i.e., **Xi,j** denotes either the observed rating if user 'i' actually rated song 'j' or the “hypothetical” such rating if user 'i' has not yet rated song 'j'.  We are interested in predicting the values of **Xi,j** that are not observed.  

Let us first consider the following model: **Xi,j = αi + βj + epsilon i,j,**

where **αi** is a coefficient that depends only on the particular row **i**(i.e., user), **βj** is a coefficient that depends only on the particular column **j**(i.e., song), and **epsilon i,j** is a noise term.

### i)
**For this dataset, how many total parameters are included in model (1)?  How many observations do we have to train the model with?**

**Use BiScaler to fit model (1) on the training data.**

In [30]:
print(f'There are a total of {songs_train_len + users_train_len} parameters in model(1).')

There are a total of 3228 parameters in model(1).

In [31]:
print(f'We have to train the model on {len(music_ratings_train)} observations.')

We have to train the model on 245997 observations.

In [34]:
# %pip install fancyimpute

In [35]:
from fancyimpute import BiScaler

### Training Set Pre-Processing

In [36]:
# Original trianing set.
music_ratings_train.sort_index()

,userID,songID,rating,songName,year,artist,genre
0,2071,581,2.484754,Show You How,2004,The Killers,Rock
1,1208,55,1.000000,Luvstruck,1999,Southside Spinners,Electronic
2,1484,510,1.000000,In One Ear,2008,Cage The Elephant,Rock
3,453,299,1.000000,Gardenhead / Leave Me Alone,1992,Neutral Milk Hotel,Rock
4,2238,113,1.000000,Hustler,2006,Simian Mobile Disco,Electronic
...,...,...,...,...,...,...,...
245992,1513,720,1.000000,Trani,2003,Kings Of Leon,Rock
245993,443,544,1.000000,A Rush Of Blood To The Head,2002,Coldplay,Rock
245994,2172,706,1.784426,Without Me,2002,Eminem,Rap
245995,1714,699,1.494918,Cherbourg,2007,Beirut,Folk
245996,2195,753,1.494918,Bitter Sweet Symphony,1997,The Verve,Pop

In [38]:
# Use pivot function so that each column is a unique song and each row is a unique user
music_ratings_train_df = music_ratings_train.pivot(index="userID", columns="songID", values="rating")
music_ratings_train_df

songID,1,2,3,4,5,6,7,8,9,10,...,798,799,800,801,802,803,804,805,806,807
userID,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.784426,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,1.989836,NaN,NaN,NaN,NaN,1.784426,NaN,NaN,1.784426,...,NaN,1.784426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,1.494918,NaN,NaN,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
5,NaN,1.000000,NaN,NaN,NaN,NaN,2.389410,NaN,NaN,2.279344,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2417,NaN,NaN,NaN,1.0,NaN,NaN,1.000000,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2418,NaN,NaN,NaN,NaN,NaN,NaN,1.494918,NaN,NaN,1.989836,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2419,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,1.000000,...,NaN,NaN,NaN,1.494918,NaN,NaN,NaN,NaN,NaN,NaN
2420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.000000,NaN,1.0,NaN,NaN,NaN,NaN
2421,NaN,1.494918,1.494918,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,...,NaN,1.494918,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
# Convert training set to matrix form
music_ratings_train_mat = music_ratings_train_df.to_numpy()
music_ratings_train_mat

array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan, 1.98983574,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan, 1.49491787, 1.49491787, ...,        nan,        nan,
               nan]], shape=(2421, 807))

In [40]:
# Making sure the number of users and songs are the same as in the training set.
print(len(np.unique(music_ratings_train.userID)))
print(music_ratings_train_mat.shape)

2421
(2421, 807)

### The Simple Additive Model through BiScaler on the Training Set

In [41]:
# The Simple Additive Model through BiScaler
music_ratings_biscaler = BiScaler(scale_rows=False, scale_columns=False, verbose=True)
music_ratings_train_mat_centered = music_ratings_biscaler.fit_transform(music_ratings_train_mat)

[BiScaler] Initial log residual value = 8.635876
[BiScaler] Iter 1: log residual = -1.278081, log improvement ratio=9.913958
[BiScaler] Iter 2: log residual = -2.464318, log improvement ratio=1.186237
[BiScaler] Iter 3: log residual = -3.599288, log improvement ratio=1.134970
[BiScaler] Iter 4: log residual = -4.728969, log improvement ratio=1.129681
[BiScaler] Iter 5: log residual = -5.851105, log improvement ratio=1.122136
[BiScaler] Iter 6: log residual = -6.961307, log improvement ratio=1.110202
[BiScaler] Iter 7: log residual = -8.052791, log improvement ratio=1.091484
[BiScaler] Iter 8: log residual = -9.115833, log improvement ratio=1.063043
[BiScaler] Iter 9: log residual = -10.137984, log improvement ratio=1.022150
[BiScaler] Iter 10: log residual = -11.105953, log improvement ratio=0.967969
[BiScaler] Iter 11: log residual = -12.009465, log improvement ratio=0.903512
[BiScaler] Iter 12: log residual = -12.845445, log improvement ratio=0.835981
[BiScaler] Iter 13: log residual = -13.619498, log improvement ratio=0.774052
[BiScaler] Iter 14: log residual = -14.343386, log improvement ratio=0.723888
[BiScaler] Iter 15: log residual = -15.030646, log improvement ratio=0.687260
[BiScaler] Iter 16: log residual = -15.693214, log improvement ratio=0.662568
[BiScaler] Iter 17: log residual = -16.340088, log improvement ratio=0.646874
[BiScaler] Iter 18: log residual = -16.977415, log improvement ratio=0.637327
[BiScaler] Iter 19: log residual = -17.609141, log improvement ratio=0.631726
[BiScaler] Iter 20: log residual = -18.237697, log improvement ratio=0.628555
[BiScaler] Iter 21: log residual = -18.864535, log improvement ratio=0.626838
[BiScaler] Iter 22: log residual = -19.490503, log improvement ratio=0.625968
[BiScaler] Iter 23: log residual = -20.116082, log improvement ratio=0.625579
[BiScaler] Iter 24: log residual = -20.741536, log improvement ratio=0.625455
[BiScaler] Iter 25: log residual = -21.367004, log improvement ratio=0.625468
[BiScaler] Iter 26: log residual = -21.992551, log improvement ratio=0.625547
[BiScaler] Iter 27: log residual = -22.618202, log improvement ratio=0.625651
[BiScaler] Iter 28: log residual = -23.243962, log improvement ratio=0.625760
[BiScaler] Iter 29: log residual = -23.869823, log improvement ratio=0.625861
[BiScaler] Iter 30: log residual = -24.495775, log improvement ratio=0.625951
[BiScaler] Iter 31: log residual = -25.121804, log improvement ratio=0.626029
[BiScaler] Iter 32: log residual = -25.747898, log improvement ratio=0.626094
[BiScaler] Iter 33: log residual = -26.374046, log improvement ratio=0.626148
[BiScaler] Iter 34: log residual = -27.000238, log improvement ratio=0.626192
[BiScaler] Iter 35: log residual = -27.626466, log improvement ratio=0.626228
[BiScaler] Iter 36: log residual = -28.252723, log improvement ratio=0.626257
[BiScaler] Iter 37: log residual = -28.879004, log improvement ratio=0.626281
[BiScaler] Iter 38: log residual = -29.505303, log improvement ratio=0.626299
[BiScaler] Iter 39: log residual = -30.131618, log improvement ratio=0.626314
[BiScaler] Iter 40: log residual = -30.757944, log improvement ratio=0.626326
[BiScaler] Iter 41: log residual = -31.384280, log improvement ratio=0.626336
[BiScaler] Iter 42: log residual = -32.010624, log improvement ratio=0.626344
[BiScaler] Iter 43: log residual = -32.636973, log improvement ratio=0.626350
[BiScaler] Iter 44: log residual = -33.263328, log improvement ratio=0.626354
[BiScaler] Iter 45: log residual = -33.889686, log improvement ratio=0.626358
[BiScaler] Iter 46: log residual = -34.516047, log improvement ratio=0.626361
[BiScaler] Iter 47: log residual = -35.142411, log improvement ratio=0.626364
[BiScaler] Iter 48: log residual = -35.768777, log improvement ratio=0.626366
[BiScaler] Iter 49: log residual = -36.395144, log improvement ratio=0.626367
[BiScaler] Iter 50: log residual = -37.021512, log improvement ratio=0.626368
[BiScaler] Iter 51: log residual = -37.647882, log improvement ratio=0.626370
[BiScaler] Iter 52: log residual = -38.274252, log improvement ratio=0.626370
[BiScaler] Iter 53: log residual = -38.900623, log improvement ratio=0.626370
[BiScaler] Iter 54: log residual = -39.526994, log improvement ratio=0.626371
[BiScaler] Iter 55: log residual = -40.153366, log improvement ratio=0.626372
[BiScaler] Iter 56: log residual = -40.779737, log improvement ratio=0.626371
[BiScaler] Iter 57: log residual = -41.406110, log improvement ratio=0.626372
[BiScaler] Iter 58: log residual = -42.032482, log improvement ratio=0.626372
[BiScaler] Iter 59: log residual = -42.658853, log improvement ratio=0.626371
[BiScaler] Iter 60: log residual = -43.285228, log improvement ratio=0.626374
[BiScaler] Iter 61: log residual = -43.911602, log improvement ratio=0.626374
[BiScaler] Iter 62: log residual = -44.537967, log improvement ratio=0.626365
[BiScaler] Iter 63: log residual = -45.164347, log improvement ratio=0.626380
[BiScaler] Iter 64: log residual = -45.790719, log improvement ratio=0.626371
[BiScaler] Iter 65: log residual = -46.417083, log improvement ratio=0.626364
[BiScaler] Iter 66: log residual = -47.043471, log improvement ratio=0.626388
[BiScaler] Iter 67: log residual = -47.669842, log improvement ratio=0.626370
[BiScaler] Iter 68: log residual = -48.296212, log improvement ratio=0.626370
[BiScaler] Iter 69: log residual = -48.922606, log improvement ratio=0.626394
[BiScaler] Iter 70: log residual = -49.548919, log improvement ratio=0.626313
[BiScaler] Iter 71: log residual = -50.175300, log improvement ratio=0.626381
[BiScaler] Iter 72: log residual = -50.801665, log improvement ratio=0.626365
[BiScaler] Iter 73: log residual = -51.428238, log improvement ratio=0.626574
[BiScaler] Iter 74: log residual = -52.054345, log improvement ratio=0.626107
[BiScaler] Iter 75: log residual = -52.680861, log improvement ratio=0.626516
[BiScaler] Iter 76: log residual = -53.307015, log improvement ratio=0.626154
[BiScaler] Iter 77: log residual = -53.933279, log improvement ratio=0.626264
[BiScaler] Iter 78: log residual = -54.559680, log improvement ratio=0.626402
[BiScaler] Iter 79: log residual = -55.187212, log improvement ratio=0.627532
[BiScaler] Iter 80: log residual = -55.813147, log improvement ratio=0.625935
[BiScaler] Iter 81: log residual = -56.439475, log improvement ratio=0.626328
[BiScaler] Iter 82: log residual = -57.063577, log improvement ratio=0.624102
[BiScaler] Iter 83: log residual = -57.693264, log improvement ratio=0.629687
[BiScaler] Iter 84: log residual = -58.321137, log improvement ratio=0.627873
[BiScaler] Iter 85: log residual = -58.939372, log improvement ratio=0.618235
[BiScaler] Iter 86: log residual = -59.564238, log improvement ratio=0.624866
[BiScaler] Iter 87: log residual = -60.192810, log improvement ratio=0.628572
[BiScaler] Iter 88: log residual = -60.822848, log improvement ratio=0.630038
[BiScaler] Iter 89: log residual = -61.436528, log improvement ratio=0.613680
[BiScaler] Iter 90: log residual = -62.056912, log improvement ratio=0.620384
[BiScaler] Iter 91: log residual = -62.706523, log improvement ratio=0.649611
[BiScaler] Iter 92: log residual = -63.233097, log improvement ratio=0.526574
[BiScaler] Iter 93: log residual = -63.841289, log improvement ratio=0.608192
[BiScaler] Iter 94: log residual = -64.418335, log improvement ratio=0.577046
[BiScaler] Iter 95: log residual = -64.887848, log improvement ratio=0.469513
[BiScaler] Iter 96: log residual = -65.264126, log improvement ratio=0.376278
[BiScaler] Iter 97: log residual = -65.576821, log improvement ratio=0.312695
[BiScaler] Iter 98: log residual = -65.796911, log improvement ratio=0.220090
[BiScaler] Iter 99: log residual = -66.009699, log improvement ratio=0.212788
[BiScaler] Iter 100: log residual = -66.096550, log improvement ratio=0.086851

In [42]:
# Access the alpha (row_mean) and beta (column_mean) values
print(music_ratings_biscaler.row_means)
print(music_ratings_biscaler.column_means)

[ 0.23597732  0.37836219 -0.12202861 ... -0.00099498 -0.09292935
 -0.07297946]
[1.1085277  1.28189302 1.45665654 1.15972853 1.28211814 1.12983062
 1.47101127 1.28577961 1.35033994 1.43749681 1.16378442 1.21511576
 1.4097627  1.23517437 1.25240525 1.18324648 1.57097994 1.24492046
 1.50054534 1.21816032 1.19678    1.45653583 1.23245392 1.1058456
 1.41882857 2.1370632  1.40920159 1.12776456 1.32721814 1.21159835
 1.11964289 1.20034543 1.17693884 1.58421436 1.45240405 1.27537058
 1.23174929 1.15390764 1.29276939 1.11644992 1.37531285 1.14228572
 1.21817148 1.26869206 1.20196407 1.18522847 1.2132076  1.20720276
 1.12599004 1.17277644 1.26637501 1.19294522 1.16589595 2.15784144
 1.7676486  1.19068097 1.12156866 1.13149055 1.85976324 1.17344651
 1.41308493 1.10785718 1.09833489 1.35995412 1.31486195 1.2667538
 1.37337888 1.11536594 1.24306441 1.45978565 1.16395292 1.21780274
 1.26713043 1.20356712 1.20973988 1.4430925  1.23889642 1.3110657
 1.39755168 1.35581768 1.15864186 1.19324072 1.13430115 1.14487043
 1.30399132 1.13730439 1.15994019 1.33331344 1.27431343 1.31721697
 1.28752372 1.30361275 1.58147094 1.24530107 1.2061634  1.0718078
 1.27755378 1.10699282 1.11540766 1.26056185 1.47398954 1.20700387
 1.13937785 1.23699031 1.0869149  1.20970922 1.23449921 1.33840688
 1.44991615 1.74087495 1.16763073 1.20800356 1.36190238 1.34651158
 1.11860529 1.22673378 1.10030854 1.15315015 1.33819031 1.34092364
 1.21167749 1.50871059 1.16105958 1.63570436 1.10467995 1.29510611
 1.12485231 1.30713779 1.14981885 1.36835615 1.48004842 1.1152586
 1.1253538  1.33463159 1.29842739 1.09673443 1.43313841 1.14262927
 1.07924578 1.26309407 1.15657735 1.4690734  1.350211   1.31066034
 1.23867954 1.40111705 1.37978693 1.32105732 1.28006133 1.11846378
 1.08616762 1.2863231  1.4672668  1.40113267 1.25853434 1.10728732
 1.07347196 1.19753431 1.12381473 1.39984124 1.34480256 1.23215276
 1.23545089 1.25362332 1.07299306 1.23525592 1.13532464 1.33927647
 1.5190952  1.10138648 1.31783513 1.21889428 1.12667453 1.21418219
 1.36681077 1.10273058 1.18453667 1.11827445 1.42595971 1.39838954
 1.44794075 1.6684241  1.25771207 1.35523303 1.12486469 1.17484332
 1.17917429 1.14941335 1.09031164 1.30081593 1.10281685 1.36976301
 1.10659594 1.22653561 1.25220119 1.14475604 1.15270628 1.19231399
 1.17704289 1.1554228  1.16291238 1.10700654 1.27426603 1.45381237
 1.10906239 1.18459451 1.1071141  1.1381874  1.37682145 1.11413522
 1.23446291 1.31342271 1.22677524 1.47507793 1.10611638 1.17190019
 1.46023745 1.17391068 1.12248701 1.12187405 1.50824059 1.53438735
 1.12407775 1.46143814 1.37423082 1.26296067 1.27382691 1.4162588
 1.22479959 1.76940782 1.13640936 1.28081887 1.15956946 1.47584396
 1.12922892 1.33014952 1.15785699 1.23997797 1.19726629 1.2318097
 1.24264365 1.27117877 1.11183026 1.59145009 1.16844692 1.14700559
 1.34106195 1.12793589 1.53967396 1.29971133 1.42788267 1.31586074
 1.1775938  1.20135125 1.09864549 1.40820726 1.25595374 1.23812319
 1.20611768 1.34276183 1.10986929 1.24517264 1.35413685 1.17328815
 1.20712315 1.22278931 1.43869107 1.14250386 1.32274607 1.18567556
 1.50200437 1.37603847 1.17610775 1.26132556 1.30732282 1.21575509
 1.21075424 1.43640478 1.12133611 1.18956514 1.2603817  1.13592783
 1.15167539 1.38751121 1.29891379 1.2244278  1.52949947 1.18163404
 1.38288434 1.1328837  1.09122194 1.1916738  1.31193097 1.30297291
 1.28976642 1.24862506 1.19104513 1.3613545  1.3148829  1.17154532
 1.18680787 1.10324909 1.18942274 1.45036834 1.28977829 1.36436378
 1.30978996 1.12096086 1.22497792 1.17725293 1.14393485 1.36445439
 1.12387227 1.23054297 1.13114332 1.36196393 1.07371177 1.25606402
 1.11427746 1.16284928 1.36697227 1.18518463 1.2433938  1.18760151
 1.16526397 1.15397521 1.11962691 1.17651092 1.14128922 1.26662652
 1.30063198 1.4299832  1.11417265 1.39637674 1.40775053 1.38131013
 1.13460497 1.60059093 1.25465124 1.2050894  1.11151488 1.36428584
 1.37935395 1.21599075 1.35144736 1.45474499 1.22731995 1.15239549
 1.62551253 1.11833667 1.2144978  1.15064307 1.16886875 1.17160989
 1.13185357 1.20659506 1.18496984 1.41482818 1.14045378 1.17436786
 1.46515148 1.48038146 1.28331063 1.17647766 1.26917288 1.17014134
 1.23068869 1.60727402 1.22088414 1.21480217 1.13839892 1.15249082
 1.13882166 1.16501422 1.46019866 1.35098831 1.10916467 1.16466948
 1.14608904 1.08417055 1.119744   1.10236392 1.2499524  1.26603061
 1.40164327 1.2074245  1.14093369 1.16381136 1.13044065 1.22351948
 1.7492032  1.19237171 1.20757409 1.19250346 1.15902816 1.31422169
 1.24576439 1.23213471 1.18107785 1.15855404 1.16533333 1.24054095
 1.11307747 1.18887253 1.10582215 1.09704996 1.18752259 1.13727512
 1.2716682  1.25498176 1.27340444 1.2176825  1.32054293 1.1650916
 1.17074761 1.16989155 1.47269276 1.40526943 1.13730834 1.20668568
 1.23373463 1.20969258 1.20769138 1.4917624  1.43159355 1.40313869
 1.54217971 1.14683195 1.10680681 1.38233864 1.20027871 1.10690447
 1.19376898 1.15594949 1.39075828 1.24811732 1.22790064 1.09466958
 2.03843682 1.12173444 1.13369874 1.21115695 1.19265176 1.15935725
 1.13022579 1.18939027 1.14607935 1.88372202 1.26380122 1.24684558
 1.14739555 1.27933605 1.11026529 1.21794591 1.34269019 1.15141038
 1.26463563 1.30601394 1.15609244 1.14971964 1.21738854 1.40599144
 1.5606785  1.11989021 1.43149557 1.24031371 1.3407034  1.1142136
 1.18303788 1.24050872 1.24839721 1.14153402 1.34323054 1.1823796
 1.10801944 1.36165522 1.10557033 1.21801104 1.11815441 1.16853261
 1.06213964 1.11130312 1.23839585 1.11715996 1.26608041 1.1986812
 1.28255306 1.09514214 1.43125797 1.21846654 1.32330994 1.18296929
 1.32344349 1.1210383  1.12141551 1.14053672 1.16940034 1.49741458
 1.28048398 1.23017698 1.40060614 1.10803195 1.45827866 1.22202509
 1.09665695 1.26176769 1.48742622 1.37369605 1.12799603 1.1333621
 1.09889482 1.54323525 1.78808272 1.10996583 1.25755391 1.18506961
 1.22937777 1.37475968 1.20787233 1.13150333 1.13375126 1.43976959
 1.26643074 1.17072431 1.31472991 1.19822354 1.32485708 1.40225405
 1.17595335 1.10878905 1.18312418 1.35642684 1.21908708 1.21666685
 1.19385726 1.14627331 1.75949699 1.19451564 1.11056185 1.4022201
 1.29299684 1.13349066 1.61284616 1.22469364 1.16219063 1.24547814
 1.21022751 1.48899008 1.12692941 1.40990447 1.1949819  1.47877422
 1.35029041 1.16260559 1.41712011 1.24678517 1.33334873 1.39959012
 1.26970635 1.23537276 1.13446103 1.53771674 1.2634043  1.17220665
 1.27417407 1.25722594 1.20429106 1.34024911 1.21807215 1.21789698
 1.12455496 1.1795571  1.18777212 1.48116254 1.30635469 1.0982002
 1.2728394  1.09533178 1.30812544 1.19922434 1.12110525 1.20348213
 1.21271351 1.39846701 1.17247865 1.13900451 1.20612023 1.12194661
 1.19824809 1.23686307 1.14895868 1.11996802 1.25975162 1.38063788
 1.62719612 1.38412114 1.09668428 1.13194338 1.1124261  1.88961032
 1.13651587 1.12640316 1.36792879 1.15869526 1.10282595 1.30765915
 1.32879479 1.221537   1.15302772 1.12439346 1.2646383  1.26648955
 1.12910668 1.27125482 1.19488913 1.10055417 1.37625093 1.14895575
 1.0833379  1.18289619 1.18126173 1.41784138 1.61435226 1.13929745
 1.18284764 1.35886417 1.25103102 1.49590959 1.32170056 1.74206993
 1.10731716 1.199918   1.23838428 1.12813964 1.78359519 1.18144712
 1.93754114 1.31527451 1.12098695 1.1681936  1.48478113 1.29165863
 1.50853976 1.19224681 1.29151449 1.21485114 1.22732218 1.19658875
 1.14613119 1.21106171 1.36579822 1.11751433 1.19592919 1.14236969
 1.19016997 1.17881792 1.29025667 1.24909661 1.1660925  1.19179442
 1.39384876 1.1877835  1.41055317 1.11468091 1.45401372 1.37629238
 1.40701038 1.15153796 1.14708796 1.35853558 1.61403532 1.16801356
 1.82817803 1.15949505 1.13046965 1.19016984 1.20828745 1.20837422
 1.26574062 1.36318721 1.34579992 1.20755438 1.13268006 1.09011352
 1.38288337 1.11282294 1.19507449 1.16214053 1.70046134 1.72982106
 1.15004894 1.16853825 1.13962903 1.13293375 1.12989066 1.12604242
 1.35996729 1.65750159 1.20532323 1.30276805 1.78659059 1.11002561
 1.1857531  1.27609887 1.24518093 1.45392585 1.37615305 1.13227092
 1.13073569 1.31745515 1.12533178 1.49611573 1.27022334 1.32176782
 1.39818449 1.41740529 1.17880294 1.10945422 1.12214802 1.22287711
 1.2742274  1.09787154 1.24624595 1.31885953 1.13578465 1.10786256
 1.13358576 1.13869603 1.1454852  1.27483809 1.35916082 1.22562253
 1.32830573 1.08582846 1.09588265 1.4986484  1.15270586 1.21838382
 1.60715049 1.28462821 1.22276593 1.14187396 1.12251343 1.25467885
 1.34898568 1.12444531 1.08993613 1.35505647 1.22388293 1.1539147
 1.50153898 1.27792328 1.43829635 1.17043197 1.20378521 1.17485278
 1.31870687 1.108771   1.14739645 1.37838411 1.5141304  1.21335471
 1.3706807  1.15458005 1.13174622 1.39438258 1.0899422  1.12579223
 1.22459976 1.33108286 1.3585659  1.26887833 1.31776921 1.10454775
 1.17321841 1.08093    1.26130861 1.25033929 1.13073873 1.29815816
 1.09894188 1.28548715 1.25271286 1.12513294 1.26867324 1.10483349
 1.2196494  1.30287037 1.1657089  1.68843587 1.27198677 1.12293945
 1.12395954 1.12329263 1.24925843 1.19655423 1.3113928  1.10448545
 1.1177122  1.17755441 1.34459901 1.20053496 1.17841101 1.2609974
 1.32111884 1.18244781 1.16531321]

#### Fitting the Simple Additive Model on the training data

In [43]:
import copy
# Copy of CENTERED matrix
music_ratings_train_mat_centered_0 = copy.copy(music_ratings_train_mat_centered)
# Replace missing values with 0, because in simple additive model, missing values
music_ratings_train_mat_centered_0[np.isnan(music_ratings_train_mat_centered_0)]=0
music_ratings_train_mat_centered_0

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.32958053, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.28600431, 0.11124078, ..., 0.        , 0.        ,
        0.        ]], shape=(2421, 807))

In [44]:
# Use inverse_transform to Transform centered table to the original table
music_ratings_BiScaler_filled = music_ratings_biscaler.inverse_transform(music_ratings_train_mat_centered_0)
music_ratings_BiScaler_filled

array([[1.34450503, 1.51787035, 1.69263387, ..., 1.55709616, 1.41842513,
        1.40129053],
       [1.4868899 , 1.98983574, 1.83501874, ..., 1.69948103, 1.56081   ,
        1.5436754 ],
       [0.98649909, 1.15986441, 1.33462793, ..., 1.19909023, 1.0604192 ,
        1.0432846 ],
       ...,
       [1.10753272, 1.28089804, 1.45566156, ..., 1.32012386, 1.18145283,
        1.16431823],
       [1.01559836, 1.18896367, 1.3637272 , ..., 1.22818949, 1.08951846,
        1.07238386],
       [1.03554825, 1.49491787, 1.49491787, ..., 1.24813938, 1.10946835,
        1.09233375]], shape=(2421, 807))

### ii)
**Using the output of the BiScaler, what are the three most popular songs after  removing  for  the  bias  due  to  users’  affinity  for  rating  songs  highly  (or  lowly)?**

**Provide the song ID numbers as well as the song and artist names for these three songs. Explain, in your own words, how your answer relates to model (1).**

In [45]:
music_ratings_train_mat_centered

array([[       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan, 0.32958053,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       ...,
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan,        nan,        nan, ...,        nan,        nan,
               nan],
       [       nan, 0.28600431, 0.11124078, ...,        nan,        nan,
               nan]], shape=(2421, 807))

In [46]:
music_ratings_BiScaler_filled

array([[1.34450503, 1.51787035, 1.69263387, ..., 1.55709616, 1.41842513,
        1.40129053],
       [1.4868899 , 1.98983574, 1.83501874, ..., 1.69948103, 1.56081   ,
        1.5436754 ],
       [0.98649909, 1.15986441, 1.33462793, ..., 1.19909023, 1.0604192 ,
        1.0432846 ],
       ...,
       [1.10753272, 1.28089804, 1.45566156, ..., 1.32012386, 1.18145283,
        1.16431823],
       [1.01559836, 1.18896367, 1.3637272 , ..., 1.22818949, 1.08951846,
        1.07238386],
       [1.03554825, 1.49491787, 1.49491787, ..., 1.24813938, 1.10946835,
        1.09233375]], shape=(2421, 807))

In [47]:
len(music_ratings_BiScaler_filled[0])

807

In [48]:
len(music_ratings_BiScaler_filled)

2421

In [49]:
# Transpose the matrix so that we can get each song into its own array.
music_ratings_BiScaler_filled.T

array([[1.34450503, 1.4868899 , 0.98649909, ..., 1.10753272, 1.01559836,
        1.03554825],
       [1.51787035, 1.98983574, 1.15986441, ..., 1.28089804, 1.18896367,
        1.49491787],
       [1.69263387, 1.83501874, 1.33462793, ..., 1.45566156, 1.3637272 ,
        1.49491787],
       ...,
       [1.55709616, 1.69948103, 1.19909023, ..., 1.32012386, 1.22818949,
        1.24813938],
       [1.41842513, 1.56081   , 1.0604192 , ..., 1.18145283, 1.08951846,
        1.10946835],
       [1.40129053, 1.5436754 , 1.0432846 , ..., 1.16431823, 1.07238386,
        1.09233375]], shape=(807, 2421))

#### Summing up the rating for each song

In [50]:
# Summing up the rating for each song and storing the total in a list
song_total_ratings = []
for i in range(len(music_ratings_BiScaler_filled.T)):
    song_total_ratings.append(sum(music_ratings_BiScaler_filled.T[i]))

In [51]:
# Every rating for each song available summed up.
song_total_ratings

[np.float64(2650.306372711403),
 np.float64(3070.0238087837743),
 np.float64(3493.1262959372984),
 np.float64(2774.263563987291),
 np.float64(3070.568820597366),
 np.float64(2701.8807254648764),
 np.float64(3527.8790868388273),
 np.float64(3079.4332260406804),
 np.float64(3235.7337990530755),
 np.float64(3446.740576932402),
 np.float64(2784.0828785063345),
 np.float64(2908.356044714126),
 np.float64(3379.5963028820775),
 np.float64(2956.9179584669178),
 np.float64(2998.6339049813137),
 np.float64(2831.200538593642),
 np.float64(3769.903243040136),
 np.float64(2980.513245058633),
 np.float64(3599.3810677951806),
 np.float64(2915.726931170478),
 np.float64(2863.965193045014),
 np.float64(3492.834050771581),
 np.float64(2950.3317461219435),
 np.float64(2643.813001663041),
 np.float64(3401.544758217399),
 np.float64(5140.390816224416),
 np.float64(3378.237841785364),
 np.float64(2696.8787893813324),
 np.float64(3179.755929265449),
 np.float64(2899.8404114300247),
 np.float64(2677.2162415116113),
 np.float64(2872.597081526899),
 np.float64(2815.929731695022),
 np.float64(3801.9437632629897),
 np.float64(3482.8310050563596),
 np.float64(3054.2329825316833),
 np.float64(2948.6258211766317),
 np.float64(2760.1711987309163),
 np.float64(3096.355499590819),
 np.float64(2669.4860467575727),
 np.float64(3296.1932143714052),
 np.float64(2732.0345378221227),
 np.float64(2915.753955650948),
 np.float64(3038.064275449628),
 np.float64(2876.5158034061387),
 np.float64(2835.998920935674),
 np.float64(2903.7363994179696),
 np.float64(2889.198672627541),
 np.float64(2692.582689240652),
 np.float64(2805.852566251504),
 np.float64(3032.45469049783),
 np.float64(2854.681185522554),
 np.float64(2789.194893276735),
 np.float64(5190.694920507644),
 np.float64(4246.038065790884),
 np.float64(2849.1994193697888),
 np.float64(2681.8785313359945),
 np.float64(2705.899411446485),
 np.float64(4469.047607252458),
 np.float64(2807.4748021497603),
 np.float64(3387.6394204738694),
 np.float64(2648.68304483175),
 np.float64(2625.6295798950437),
 np.float64(3259.009718693075),
 np.float64(3149.841586449112),
 np.float64(3033.3717492029073),
 np.float64(3291.511072464021),
 np.float64(2666.86173228562),
 np.float64(2976.0197318872315),
 np.float64(3500.701862859383),
 np.float64(2784.490819703528),
 np.float64(2914.8612295521584),
 np.float64(3034.2835608556593),
 np.float64(2880.3967937417515),
 np.float64(2895.341049985774),
 np.float64(3460.287740437674),
 np.float64(2965.929045258706),
 np.float64(3140.6508716978065),
 np.float64(3350.0334177628156),
 np.float64(3248.995409642364),
 np.float64(2771.6327550358365),
 np.float64(2855.396580756601),
 np.float64(2712.7038741660713),
 np.float64(2738.2921064939633),
 np.float64(3123.5237747984083),
 np.float64(2719.9747302628953),
 np.float64(2774.776001238376),
 np.float64(3194.5126492623317),
 np.float64(3051.67361072674),
 np.float64(3155.5430970875864),
 np.float64(3083.655718631241),
 np.float64(3122.6072797685624),
 np.float64(3795.301952040625),
 np.float64(2981.4346802292234),
 np.float64(2886.682384276835),
 np.float64(2561.4074843428257),
 np.float64(3059.518503008217),
 np.float64(2646.590425985593),
 np.float64(2666.962734337917),
 np.float64(3018.3810292910107),
 np.float64(3535.0894786228687),
 np.float64(2888.7171648595286),
 np.float64(2724.994575918943),
 np.float64(2961.3143395104025),
 np.float64(2597.9817840011765),
 np.float64(2895.2668280845774),
 np.float64(2955.283384745703),
 np.float64(3206.8438538675964),
 np.float64(3476.8077886534825),
 np.float64(4181.219059059472),
 np.float64(2793.3948056979275),
 np.float64(2891.1374280728355),
 np.float64(3263.7264697118208),
 np.float64(3226.4653289655207),
 np.float64(2674.704196356152),
 np.float64(2936.4832881879106),
 np.float64(2630.4077725684074),
 np.float64(2758.3373125731728),
 np.float64(3206.319551880006),
 np.float64(3212.9369379947),
 np.float64(2900.032000040146),
 np.float64(3619.1491402665747),
 np.float64(2777.4860492614707),
 np.float64(3926.6010521798585),
 np.float64(2640.990956197274),
 np.float64(3102.0126857041223),
 np.float64(2689.8282413710726),
 np.float64(3131.141391513662),
 np.float64(2750.272233276432),
 np.float64(3279.351033475896),
 np.float64(3549.7580314017155),
 np.float64(2666.6018742363235),
 np.float64(2691.04234494703),
 np.float64(3197.703876942158),
 np.float64(3110.0535048955207),
 np.float64(2621.754849697242),
 np.float64(3436.188884370526),
 np.float64(2732.866265083085),
 np.float64(2579.414827278963),
 np.float64(3024.5115379429653),
 np.float64(2766.6345563982563),
 np.float64(3523.1874918348108),
 np.float64(3235.421637482319),
 np.float64(3139.669483947044),
 np.float64(2965.40396187248),
 np.float64(3358.6651737636603),
 np.float64(3307.02495305918),
 np.float64(3164.840578687284),
 np.float64(3065.5892714514284),
 np.float64(2674.361611762781),
 np.float64(2596.172599090382),
 np.float64(3080.7490372481784),
 np.float64(3518.8137226026583),
 np.float64(3358.70300363094),
 np.float64(3013.4724357954196),
 np.float64(2647.303398134827),
 np.float64(2565.436410447512),
 np.float64(2865.7913551651413),
 np.float64(2687.3162709218054),
 np.float64(3355.576450719238),
 np.float64(3222.3278042581683),
 np.float64(2949.6026294273806),
 np.float64(2957.5874130354487),
 np.float64(3001.582848464042),
 np.float64(2564.2769945618516),
 np.float64(2957.115393826734),
 np.float64(2715.1817430126894),
 np.float64(3208.949136384645),
 np.float64(3644.2902683148227),
 np.float64(2633.0174663328194),
 np.float64(3157.0396454502056),
 np.float64(2917.5038553263144),
 np.float64(2694.2398493722103),
 np.float64(2906.0958946365645),
 np.float64(3275.6096695669557),
 np.float64(2636.2715396847757),
 np.float64(2834.3240878542742),
 np.float64(2673.9032361344002),
 np.float64(3418.809269389385),
 np.float64(3352.0618664453823),
 np.float64(3472.0253643237916),
 np.float64(4005.815540320235),
 np.float64(3011.481711830701),
 np.float64(3247.5799602622083),
 np.float64(2689.858204805159),
 np.float64(2810.8564677152062),
 np.float64(2821.3417599360596),
 np.float64(2749.2905196367997),
 np.float64(2606.205278298339),
 np.float64(3115.8361672893916),
 np.float64(2636.4803906762813),
 np.float64(3282.7570415233176),
 np.float64(2645.6295625054177),
 np.float64(2936.0035202899385),
 np.float64(2998.139877530228),
 np.float64(2738.0151827626187),
 np.float64(2757.2627145565625),
 np.float64(2853.152982093775),
 np.float64(2816.1816336001248),
 np.float64(2763.8393914928506),
 np.float64(2781.9716668593987),
 np.float64(2646.6236318228534),
 np.float64(3051.5588694444273),
 np.float64(3486.240548327148),
 np.float64(2651.600841210232),
 np.float64(2834.4641005981075),
 np.float64(2646.884048855985),
 np.float64(2722.1124921623477),
 np.float64(3299.8455273189343),
 np.float64(2663.882179684389),
 np.float64(2955.195498380403),
 np.float64(3146.3571920022987),
 np.float64(2936.5836528546647),
 np.float64(3537.724461050433),
 np.float64(2644.4685455077315),
 np.float64(2803.731149960225),
 np.float64(3501.7956738713724),
 np.float64(2808.5985664366463),
 np.float64(2684.1018532518965),
 np.float64(2682.61787885333),
 np.float64(3618.011271884882),
 np.float64(3681.312569059875),
 np.float64(2687.953032592769),
 np.float64(3504.702530088429),
 np.float64(3293.573605002796),
 np.float64(3024.1885770609797),
 np.float64(3050.4957502903862),
 np.float64(3395.323355336962),
 np.float64(2931.8005980527378),
 np.float64(4250.297135969595),
 np.float64(2717.807850420049),
 np.float64(3067.4232753747556),
 np.float64(2773.878453321022),
 np.float64(3539.579039045336),
 np.float64(2700.424013973038),
 np.float64(3186.8527964315463),
 np.float64(2769.7325669460647),
 np.float64(2968.547462426304),
 np.float64(2865.142486786349),
 np.float64(2948.772080832667),
 np.float64(2975.0010880614363),
 np.float64(3044.084603343732),
 np.float64(2658.301854720006),
 np.float64(3819.461479759309),
 np.float64(2795.3707878188093),
 np.float64(2743.4613229827223),
 np.float64(3213.2717725923007),
 np.float64(2697.293589446603),
 np.float64(3694.111455336451),
 np.float64(3113.1619319930887),
 np.float64(3423.4647475620773),
 np.float64(3152.2596442648132),
 np.float64(2817.5153940111663),
 np.float64(2875.0321791724496),
 np.float64(2626.3815329565396),
 np.float64(3375.8305781436593),
 np.float64(3007.2248049962145),
 np.float64(2964.0570333613555),
 np.float64(2886.5717136789704),
 np.float64(3217.387193104996),
 np.float64(2653.5543503964564),
 np.float64(2981.1237590448204),
 np.float64(3244.9261134701565),
 np.float64(2807.091417456838),
 np.float64(2889.005944445944),
 np.float64(2926.9337134819),
 np.float64(3449.6318889089616),
 np.float64(2732.5626555789995),
 np.float64(3168.9290421530936),
 np.float64(2837.081338981737),
 np.float64(3602.9133712763987),
 np.float64(3297.949946128757),
 np.float64(2813.917672449461),
 np.float64(3020.2299879917073),
 np.float64(3131.589359120282),
 np.float64(2909.9038684875245),
 np.float64(2897.7968115067188),
 np.float64(3444.0967702558896),
 np.float64(2681.315527880294),
 np.float64(2846.498005729354),
 np.float64(3017.9448945444524),
 np.float64(2716.6420779646387),
 np.float64(2754.7669225771333),
 np.float64(3325.725437240315),
 np.float64(3111.2310757427813),
 np.float64(2930.9005137954514),
 np.float64(3669.4790167368797),
 np.float64(2827.29681599595),
 np.float64(3314.523798278096),
 np.float64(2709.2722410664433),
 np.float64(2608.409123219914),
 np.float64(2851.6030632719867),
 np.float64(3142.74569089346),
 np.float64(3121.0582071422273),
 np.float64(3089.0853154216097),
 np.float64(2989.482071185959),
 np.float64(2850.0810524605945),
 np.float64(3262.400036434889),
 np.float64(3149.892301259223),
 np.float64(2802.8720212287008),
 np.float64(2839.8226548717143),
 np.float64(2637.5268456858507),
 np.float64(2846.15326130074),
 np.float64(3477.902544990754),
 np.float64(3089.114046488823),
 np.float64(3269.6855012247343),
 np.float64(3137.5622922984385),
 np.float64(2680.4070475385884),
 np.float64(2932.232353462877),
 np.float64(2816.6901518386835),
 np.float64(2736.027065158603),
 np.float64(3269.9048859660984),
 np.float64(2687.4555561333445),
 np.float64(2945.7053299485688),
 np.float64(2705.0587688120595),
 np.float64(3263.8754864217667),
 np.float64(2566.0169888398736),
 np.float64(3007.4917822007274),
 np.float64(2664.226526906772),
 np.float64(2781.818909004811),
 np.float64(3276.000658952837),
 np.float64(2835.8927931660955),
 np.float64(2976.8171890560525),
 np.float64(2841.7440518018934),
 np.float64(2787.6648652065783),
 np.float64(2760.334777487803),
 np.float64(2677.177548040794),
 np.float64(2814.893743228571),
 np.float64(2729.6220087994116),
 np.float64(3033.0636043939803),
 np.float64(3115.390815202888),
 np.float64(3428.5501165710643),
 np.float64(2663.9727806055303),
 np.float64(3347.1888896252008),
 np.float64(3374.724833947539),
 np.float64(3310.712625776063),
 np.float64(2713.439424728101),
 np.float64(3841.591435361058),
 np.float64(3004.071459738853),
 np.float64(2884.082231749083),
 np.float64(2657.5383250956324),
 np.float64(3269.49681902687),
 np.float64(3305.9767163124875),
 np.float64(2910.4744069708977),
 np.float64(3238.4148546864967),
 np.float64(3488.498430478681),
 np.float64(2937.902393869215),
 np.float64(2756.510279984077),
 np.float64(3901.9266337902573),
 np.float64(2674.0538713063997),
 np.float64(2906.85997987062),
 np.float64(2752.267682722363),
 np.float64(2796.3920382664946),
 np.float64(2803.0283562765767),
 np.float64(2706.7783053941944),
 np.float64(2887.7274354670017),
 np.float64(2835.372783466873),
 np.float64(3391.859821210909),
 np.float64(2727.5993986502176),
 np.float64(2809.7053918478073),
 np.float64(3513.692538047803),
 np.float64(3550.564305539474),
 np.float64(3073.4558316424477),
 np.float64(2814.8132054735956),
 np.float64(3039.2283476696894),
 np.float64(2799.472988144368),
 np.float64(2946.05813005565),
 np.float64(3857.771207939008),
 np.float64(2922.3213036377974),
 np.float64(2907.5968588072014),
 np.float64(2722.6245763730426),
 np.float64(2756.7410862521806),
 np.float64(2723.6480331459643),
 np.float64(2787.0602179794582),
 np.float64(3501.7017474704726),
 np.float64(3237.303498470941),
 np.float64(2651.848462456622),
 np.float64(2786.225609883146),
 np.float64(2741.2423597625325),
 np.float64(2591.337697337422),
 np.float64(2677.4610328859003),
 np.float64(2635.3838508971053),
 np.float64(2992.6955498804823),
 np.float64(3031.6208981324176),
 np.float64(3359.9391592005886),
 np.float64(2889.735523298491),
 np.float64(2728.7612740528352),
 np.float64(2784.148109228862),
 np.float64(2703.357619822186),
 np.float64(2928.701452249577),
 np.float64(4201.381739544764),
 np.float64(2853.292714857828),
 np.float64(2890.0976731830106),
 np.float64(2853.611682438603),
 np.float64(2772.5679657136075),
 np.float64(3148.291513913334),
 np.float64(2982.5563983513425),
 np.float64(2949.5589272917205),
 np.float64(2825.9502701899864),
 np.float64(2771.420122202426),
 np.float64(2787.832791674468),
 np.float64(2969.9104429175004),
 np.float64(2661.3213498124214),
 np.float64(2844.8211910458253),
 np.float64(2643.756231358314),
 np.float64(2622.518742605012),
 np.float64(2841.553000563018),
 np.float64(2719.903877944194),
 np.float64(3045.2695244160036),
 np.float64(3004.8716497282085),
 np.float64(3049.4729473614484),
 np.float64(2914.570135417883),
 np.float64(3163.5952403256592),
 np.float64(2787.2475622345096),
 np.float64(2800.9407752902384),
 np.float64(2798.8682486672496),
 np.float64(3531.9499624619416),
 np.float64(3368.7180819727955),
 np.float64(2719.984280462621),
 np.float64(2887.9468216193486),
 np.float64(2953.4323322223063),
 np.float64(2895.2265281040786),
 np.float64(2890.38162751125),
 np.float64(3578.11756665777),
 np.float64(3432.4487790860753),
 np.float64(3363.559570335528),
 np.float64(3700.1778863775558),
 np.float64(2743.0409442967625),
 np.float64(2646.140095538143),
 np.float64(3313.2026601831735),
 np.float64(2872.435557479003),
 np.float64(2646.376521812422),
 np.float64(2856.675511168178),
 np.float64(2765.114527243924),
 np.float64(3333.5865908185624),
 np.float64(2988.2528326090455),
 np.float64(2939.3082437808853),
 np.float64(2616.7558479157665),
 np.float64(4901.616334352098),
 np.float64(2682.2798744508527),
 np.float64(2711.245460031291),
 np.float64(2898.7717704662327),
 np.float64(2853.970722255623),
 np.float64(2773.364701454735),
 np.float64(2702.837429176238),
 np.float64(2846.074647608373),
 np.float64(2741.2189045948103),
 np.float64(4527.051807196002),
 np.float64(3026.223551541634),
 np.float64(2985.173953195834),
 np.float64(2744.4054392579783),
 np.float64(3063.833374644447),
 np.float64(2654.51306578218),
 np.float64(2915.2078378884107),
 np.float64(3217.2137622637606),
 np.float64(2754.1253416455265),
 np.float64(3028.2436628037885),
 np.float64(3128.420542018899),
 np.float64(2765.46060105198),
 np.float64(2750.0320513026168),
 np.float64(2913.858455601155),
 np.float64(3370.4660745840383),
 np.float64(3744.963441623385),
 np.float64(2677.814999543473),
 np.float64(3432.2115676316757),
 np.float64(2969.3602841512675),
 np.float64(3212.4037274312504),
 np.float64(2664.0719192647375),
 np.float64(2830.695512608014),
 np.float64(2969.8324017294813),
 np.float64(2988.930455726966),
 np.float64(2730.2146610548075),
 np.float64(3218.521931836297),
 np.float64(2829.1018028417234),
 np.float64(2649.0758567518606),
 np.float64(3263.1280774008906),
 np.float64(2643.1465785354385),
 np.float64(2915.365540650075),
 np.float64(2673.6126357678863),
 np.float64(2795.5782403343273),
 np.float64(2538.000859739849),
 np.float64(2657.0256483968924),
 np.float64(2964.7171449539087),
 np.float64(2671.2050684819083),
 np.float64(3031.741480190457),
 np.float64(2868.5679940579157),
 np.float64(3071.6217710392066),
 np.float64(2617.899932371001),
 np.float64(3431.6363421189158),
 np.float64(2916.468297224806),
 np.float64(3170.2941682549786),
 np.float64(2830.5294519427116),
 np.float64(3170.6174899335415),
 np.float64(2680.5945156282082),
 np.float64(2681.507748905586),
 np.float64(2727.800204405742),
 np.float64(2797.679032442945),
 np.float64(3591.8014926294377),
 np.float64(3066.6125166953157),
 np.float64(2944.8192799988365),
 np.float64(3357.428272671275),
 np.float64(2649.1061594747807),
 np.float64(3497.0534296627843),
 np.float64(2925.0835491459493),
 np.float64(2621.5672714276816),
 np.float64(3021.300388271388),
 np.float64(3567.6196908430798),
 np.float64(3292.2789362238923),
 np.float64(2697.4391812690455),
 np.float64(2710.4304531811335),
 np.float64(2626.985155387584),
 np.float64(3702.7333339286747),
 np.float64(4295.509057292724),
 np.float64(2653.78807722325),
 np.float64(3011.098828850997),
 np.float64(2835.6143211049757),
 np.float64(2942.884378455917),
 np.float64(3294.853983700772),
 np.float64(2890.819718837805),
 np.float64(2705.9303577985156),
 np.float64(2711.3725917379375),
 np.float64(3452.2429775043015),
 np.float64(3032.58961362749),
 np.float64(2800.88435497034),
 np.float64(3149.5219137309527),
 np.float64(2867.4599816336713),
 np.float64(3174.0397916975508),
 np.float64(3361.4178597801274),
 np.float64(2813.543861871095),
 np.float64(2650.9390945759656),
 np.float64(2830.9044517367493),
 np.float64(3250.470177233105),
 np.float64(2917.9706228059326),
 np.float64(2912.1112555486197),
 np.float64(2856.889228638123),
 np.float64(2741.688477110087),
 np.float64(4226.303002411088),
 np.float64(2858.483169979147),
 np.float64(2655.231043542946),
 np.float64(3361.3356653697087),
 np.float64(3096.906159930405),
 np.float64(2710.741695777859),
 np.float64(3871.261359485126),
 np.float64(2931.5440924109503),
 np.float64(2780.2243235127708),
 np.float64(2981.863369708892),
 np.float64(2896.5216068982854),
 np.float64(3571.405777459651),
 np.float64(2694.8568921376204),
 np.float64(3379.9395132905815),
 np.float64(2859.611985467497),
 np.float64(3546.673185647312),
 np.float64(3235.613874721223),
 np.float64(2781.2289311371637),
 np.float64(3397.408596725171),
 np.float64(2985.0276995605545),
 np.float64(3194.598086981587),
 np.float64(3354.9684893338544),
 np.float64(3040.519879899669),
 np.float64(2957.3982610838684),
 np.float64(2713.0909593869223),
 np.float64(3689.3730339183803),
 np.float64(3025.2626123855607),
 np.float64(2804.473093802625),
 np.float64(3051.336213713094),
 np.float64(3010.30480335798),
 np.float64(2882.149445523223),
 np.float64(3211.3038881569532),
 np.float64(2915.513470792638),
 np.float64(2915.089381114301),
 np.float64(2689.1083526910625),
 np.float64(2822.2685389969556),
 np.float64(2842.157092569299),
 np.float64(3552.4553198440417),
 np.float64(3129.2454954122354),
 np.float64(2625.303479435335),
 np.float64(3048.1049931112293),
 np.float64(2618.359052116931),
 np.float64(3133.5324855446584),
 np.float64(2869.8829191402033),
 np.float64(2680.756603105987),
 np.float64(2880.1910287271403),
 np.float64(2902.5401969298946),
 np.float64(3352.2494322811617),
 np.float64(2805.131612366691),
 np.float64(2724.0907222005744),
 np.float64(2886.57787745018),
 np.float64(2682.7935342564742),
 np.float64(2867.5194193400644),
 np.float64(2961.0062941716683),
 np.float64(2748.189756208963),
 np.float64(2678.0033865265273),
 np.float64(3016.419481790059),
 np.float64(3309.085105770371),
 np.float64(3906.0025991574903),
 np.float64(3317.518069394037),
 np.float64(2621.633446914698),
 np.float64(2706.995719717261),
 np.float64(2659.744386113094),
 np.float64(4541.307388147829),
 np.float64(2718.065710435707),
 np.float64(2693.5828559829615),
 np.float64(3278.316391137686),
 np.float64(2771.762018287359),
 np.float64(2636.5024149799433),
 np.float64(3132.403610783721),
 np.float64(3183.57299869899),
 np.float64(2923.9018691248893),
 np.float64(2758.0409110663572),
 np.float64(2688.7173587664724),
 np.float64(3028.2501223339987),
 np.float64(3032.732010082039),
 np.float64(2700.1280843020186),
 np.float64(3044.268720081917),
 np.float64(2859.387377964372),

In [52]:
# The top 3 highest ratings
top_three_ratings = sorted(song_total_ratings, reverse=True)[:3]
top_three_ratings

[np.float64(5190.694920507644),
 np.float64(5140.390816224416),
 np.float64(4901.616334352098)]